name: updater
description: Upload and Download App Updates.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.1
  filesystem_picker: ^3.1.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.7.0
  freezed_annotation: ^2.0.3
  go_router: ^5.2.0
  desktop_window: ^0.4.0
  lumberdash: ^3.0.0
  colorize_lumberdash: ^3.0.0
  flutter_riverpod: ^2.1.1
  desktop_lifecycle: ^0.1.0
  app_links: ^3.3.0
  collection: ^1.16.0
  path_provider: ^2.0.11
  process_run: ^0.12.3+2
  supabase_flutter: ^1.1.0
  supa_manager:
    path: ../supa_manager
  utilities:
    path: ../utilities/
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  freezed: ^2.1.0+1

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/secrets.json
